services:
  tunnel:
    image: cloudflare/cloudflared:2023.8.1
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app-api
      - user-app

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - postgres_data:/var/lib/postgresql

  garage:
    image: dxflrs/garage:v2.1.0
    volumes:
      - ./storage/garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    restart: always

  app-api:
    build:
      context: .
      dockerfile: server/App.Api/Dockerfile 
    depends_on:
      db:
        condition: service_healthy
      garage:
        condition: service_started
    environment:
      AppDatabase__DatabaseProvider: "postgres"
      AppDatabase__ConnectionString: "Host=db;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ContentStore__UploadWindowMinutes: 5
      ContentStore__DownloadWindowMinutes: 5
      MinIo__AccessKey: "${GARAGE_APP_KEY}"
      MinIo__SecretKey: "${GARAGE_APP_SECRET}"
      MinIo__ExternalEndpoint: "${CONTENT_STORE_DOMAIN}"
      MinIo__InternalEndpoint: garage:${GARAGE_API_PORT}
      MinIo__Region: "${GARAGE_REGION}"
      MinIo__Bucket: "${CONTENT_STORE_MAIN_BUCKET}"
      MinIo__UseSsl: true 
      SessionAuth__SessionDurationMinutes: 240 
      DataProtection__KeystorePath: "/var/lib/dp_keys"
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    volumes:
      - dp_keys:/var/lib/dp_keys

  internal-api:
    build:
      context: .
      dockerfile: server/Internal.Api/Dockerfile 
    depends_on:
      db:
          condition: service_healthy
      garage:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      AppDatabase__DatabaseProvider: "postgres"
      AppDatabase__ConnectionString: "Host=db;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      ContentStore__UploadWindowMinutes: 5
      ContentStore__DownloadWindowMinutes: 5
      MinIo__ContentStoreProvider: "s3"
      MinIo__AccessKey: "${GARAGE_APP_KEY}"
      MinIo__SecretKey: "${GARAGE_APP_SECRET}"
      MinIo__ExternalEndpoint: "${CONTENT_STORE_DOMAIN}"
      MinIo__InternalEndpoint: garage:${GARAGE_API_PORT}
      MinIo__Region: "${GARAGE_REGION}"
      MinIo__Bucket: "${CONTENT_STORE_MAIN_BUCKET}"
      MinIo__UseSsl: false 
      DOTNET_ENVIRONMENT: "Production"
    restart: no

  user-app:
    build:
      context: ./client/photodump-user
      dockerfile: Dockerfile
    depends_on:
      - app-api
    environment:
      APP_API_URL: "http://app-api:8080"

volumes:
  postgres_data:
  garage_meta:
  garage_data:
  dp_keys: