CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "EventStates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StateName" character varying(255) NOT NULL,
    CONSTRAINT "PK_EventStates" PRIMARY KEY ("Id")
);

CREATE TABLE "EventTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TypeName" character varying(255) NOT NULL,
    CONSTRAINT "PK_EventTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "MediaTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileExtension" character varying(24) NOT NULL,
    CONSTRAINT "PK_MediaTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Events" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventName" text NOT NULL,
    "EventDate" timestamp with time zone NOT NULL,
    "DurationDays" integer NOT NULL,
    "EventPasswordHash" text NOT NULL,
    "EventStateId" integer NOT NULL,
    "EventTypeId" integer NOT NULL,
    CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Events_EventStates_EventStateId" FOREIGN KEY ("EventStateId") REFERENCES "EventStates" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Events_EventTypes_EventTypeId" FOREIGN KEY ("EventTypeId") REFERENCES "EventTypes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Admins" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(255) NOT NULL,
    "Email" text NOT NULL,
    "EventId" integer NOT NULL,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Admins_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Guests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(255) NOT NULL,
    "EventId" integer NOT NULL,
    CONSTRAINT "PK_Guests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Guests_Events_EventId" FOREIGN KEY ("EventId") REFERENCES "Events" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Media" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text NOT NULL,
    "OriginalSize" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "DownloadCount" integer NOT NULL DEFAULT 0,
    "Url" text NOT NULL,
    "IsPrivate" boolean NOT NULL DEFAULT TRUE,
    "GuestId" integer NOT NULL,
    "MediaTypeId" integer NOT NULL,
    CONSTRAINT "PK_Media" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Media_Guests_GuestId" FOREIGN KEY ("GuestId") REFERENCES "Guests" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Media_MediaTypes_MediaTypeId" FOREIGN KEY ("MediaTypeId") REFERENCES "MediaTypes" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Admins_EventId" ON "Admins" ("EventId");

CREATE INDEX "IX_Events_EventStateId" ON "Events" ("EventStateId");

CREATE INDEX "IX_Events_EventTypeId" ON "Events" ("EventTypeId");

CREATE INDEX "IX_Guests_EventId" ON "Guests" ("EventId");

CREATE INDEX "IX_Media_GuestId" ON "Media" ("GuestId");

CREATE INDEX "IX_Media_MediaTypeId" ON "Media" ("MediaTypeId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251026151734_InitialCreate', '9.0.10');

COMMIT;

